import {HAZARDS,classifyIntent} from '/modules/playbooks.js';
import {getBrief} from '/modules/briefs.js';
import {CITIES,OFFICES,COASTS,searchCities,rememberCity,recalledCity,rememberCoast,recalledCoast,locateCities,requestPosition,locationError} from '/modules/locations.js';
import {loadSnapshot} from '/modules/monitoring.js';
import {isSnapshotFresh,warningSummary,jstTime} from '/modules/client.js';
import {snapshotAlerts,eventKey,nextInterrupt,alertView,countdown} from '/modules/alerts.js';
import {SHELTER_TYPES,nearbyShelters,navigationURL} from '/modules/shelters.js';
const $=s=>document.querySelector(s), t=(ja,zh)=>lang==='zh'?zh:ja;
let lang=localStorage.getItem('mamori-language')==='zh'?'zh':'ja';
let selected=recalledCity(localStorage),snapshot=null,busy=false,request=0,currentGuide=null,blocked=false,activeAlert=null,shelterRequest=0,recognition=null,locationRequest=0;
let seen;try{seen=new Set(JSON.parse(localStorage.getItem('mamori-seen-alerts')||'[]'));}catch{seen=new Set();}
const labels={earthquake:['地震','地震','揺'],tsunami:['津波','海啸','波'],landslide:['土砂災害','滑坡泥石流','山'],flood:['大雨・洪水','暴雨洪水','雨'],typhoon:['台風','台风','風'],volcano:['火山','火山','火'],prepare:['日ごろの備え','日常准备','備']};
function node(tag,cls,txt){const n=document.createElement(tag);if(cls)n.className=cls;if(txt!==undefined)n.textContent=txt;return n;}
function link(label,url){const n=node('a','',label);n.href=url;n.target='_blank';n.rel='noopener';return n;}
function empty(el,text){el.replaceChildren(node('p','empty',text));}
function option(text,value){return new Option(text,value);}
function show(dialog){if(!dialog.open)dialog.showModal();}
function fillCities(){const code=$('#office').value;$('#city').replaceChildren(option('— 市区町村 —',''),...CITIES.filter(c=>c.officeCode===code).map(c=>option(c.name,c.code)));$('#city').disabled=!code;if(selected?.officeCode===code)$('#city').value=selected.code;}
function chooseCity(city){locationRequest++;selected=rememberCity(city.code,localStorage);$('#office').value=city.officeCode;fillCities();$('#city').value=city.code;$('#coast').value=recalledCoast(localStorage);$('#address-candidates').replaceChildren();$('#location-message').textContent=t('確認した市町村を保存しました。','已保存确认的市町村。');snapshot=null;busy=false;refresh();}
function candidates(items){$('#address-candidates').replaceChildren(...items.slice(0,30).map(c=>{const b=node('button','',c.office+' '+c.name);b.onclick=()=>chooseCity(c);return b;}));$('#location-message').textContent=items.length?t('市町村を確認して選択してください。','请核对市町村后确认。'):t('該当候補なし。市町村名・7桁郵便番号、または地域一覧を使用。','未找到候选，请输入市町村名或7位邮编，也可使用地区列表。');}
function findAddress(){locationRequest++;candidates(searchCities($('#address-query').value));}
$('#location-form').onsubmit=e=>{e.preventDefault();findAddress();};
$('#office').replaceChildren(option('— 地域 —',''),...OFFICES.map(o=>option(o.name,o.code)));
$('#office').onchange=fillCities;$('#city').onchange=()=>{const c=CITIES.find(c=>c.code===$('#city').value);if(c)chooseCity(c);};
$('#coast').replaceChildren(option('— 津波沿岸 / 海啸沿岸 —',''),...COASTS.map(c=>option(c[0],c[0])));
$('#coast').value=recalledCoast(localStorage);$('#coast').onchange=()=>{if($('#coast').value)rememberCoast($('#coast').value,localStorage);else localStorage.removeItem('mamori-confirmed-coast');snapshot=null;busy=false;refresh();};
$('#gps').onclick=async()=>{const id=++locationRequest;$('#gps').disabled=true;$('#location-message').textContent=t('位置情報を確認中…','正在定位…');try{const result=await locateCities(navigator.geolocation);if(id===locationRequest)candidates(result.cities);}catch(e){if(id===locationRequest)$('#location-message').textContent=locationError(e,lang);}finally{$('#gps').disabled=false;}};
$('#voice-address').onclick=()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('#location-message').textContent=t('このブラウザは音声入力に未対応。入力欄を使用。','当前浏览器不支持语音，请使用输入框。');return;}recognition?.abort();recognition=new Recognition();recognition.lang=lang==='ja'?'ja-JP':'zh-CN';recognition.onresult=e=>{$('#address-query').value=e.results[0][0].transcript;findAddress();};recognition.onerror=()=>{$('#location-message').textContent=t('音声入力を完了できません。文字入力を使用。','语音输入未完成，请使用文字输入。');};recognition.start();};
function hazards(){for(const [selector,list]of [['#quick-hazards',HAZARDS.slice(0,4)],['#all-hazards',HAZARDS]])$(selector).replaceChildren(...list.map(h=>{const b=node('button','hazard-button'),g=getBrief(h,lang);b.append(node('span','hazard-icon',labels[h][2]),node('strong','',labels[h][lang==='zh'?1:0]));if(selector==='#all-hazards')b.append(node('p','',g.action));b.onclick=()=>openGuide(h);return b;}));}
function renderData(){const fresh=navigator.onLine&&isSnapshotFresh(snapshot);$('#data-badge').classList.toggle('live',fresh);$('#data-badge').textContent=busy?t('確認中','查询中'):fresh?t('公式データ取得','已取得官方数据'):t('最新状態未確認','最新状态未确认');$('#status-title').textContent=selected?selected.office+' '+selected.name:t('まず、場所を教えてください。','先确认你的所在地。');$('#status-copy').textContent=selected?warningSummary(fresh?snapshot:null,lang):t('GPS・音声/住所・地域一覧・郵便番号から場所を設定。','通过 GPS、语音/地址、地区列表或邮编设置所在地。');$('#checked').textContent=snapshot?t('取得 ','查询 ')+jstTime(snapshot.checkedAt):'';
 $('#warning-list').replaceChildren(...snapshotAlerts(snapshot).map(a=>{const row=node('div','alert-row'),info=node('div');info.append(node('strong','',a.name),node('small','alert-detail',(fresh?'':t('過去の記録 · ','历史记录 · '))+a.city+' · '+jstTime(a.issuedAt)));const b=node('button','',t('詳細・行動 →','详情与应对 →'));b.onclick=()=>openAlert(a);row.append(info,b);return row;}));
 const forecast=fresh&&!snapshot?.forecast?.stale?snapshot?.forecast:null;
 if(forecast){$('#forecast').replaceChildren(...forecast.days.slice(0,3).map(d=>{const box=node('div','forecast-day');box.append(node('small','',d.dateTime?.slice(5,10)||''),node('strong','',d.condition));return box;}));$('#forecast-source').replaceChildren(link(forecast.area+' · '+jstTime(forecast.issuedAt)+' ↗',forecast.source));}else{empty($('#forecast'),t('最新の天気を確認できていません。','尚未确认最新天气。'));$('#forecast-source').replaceChildren();}
 const national=snapshot?.national||[];if(national.length)$('#national').replaceChildren(...national.slice(0,6).map(e=>{const box=node('div','national-item');box.append(link(e.title+' ↗',e.id),node('p','',e.summary),node('small','',jstTime(e.issuedAt)));return box;}));else empty($('#national'),t('全国の発表記録は未取得。','尚未取得全国发布记录。'));}
async function refresh(){if(busy)return;if(!selected){$('#address-query').focus();return;}const id=++request;busy=true;$('#refresh').disabled=true;renderData();try{const result=await loadSnapshot(selected.code,recalledCoast(localStorage),true);if(id!==request)return;snapshot=result;localStorage.setItem('mamori-public-snapshot',JSON.stringify(result));const interrupt=nextInterrupt(result,seen);if(interrupt){seen.add(eventKey(interrupt));localStorage.setItem('mamori-seen-alerts',JSON.stringify([...seen].slice(-80)));openAlert(interrupt);}}catch{if(id===request)snapshot=null;}finally{if(id===request){busy=false;$('#refresh').disabled=false;renderData();if(activeAlert)renderAlert();}}}
$('#refresh').onclick=refresh;
function updateHud(){const g=getBrief(currentGuide||'prepare',lang,blocked);$('#hud-count').textContent=t('一画面','一屏');$('#hud-title').textContent=g.action;$('#hud-detail').textContent=g.points.map(p=>'• '+p.text).join('\n');}
function openGuide(h,b=false){currentGuide=h;blocked=b;renderGuide();show($('#guide-dialog'));}
function renderGuide(){const g=getBrief(currentGuide,lang,blocked);$('#guide-category').textContent=g.title+' · '+t('オフライン','离线');$('#guide-title').textContent=g.action;$('#guide-points').replaceChildren(...g.points.map(p=>node('li','',p.text)));$('#guide-source').href=g.source;$('#guide-message').textContent=g.footer;$('#blocked-choice').hidden=blocked||!['flood','landslide'].includes(currentGuide);updateHud();}
$('#blocked-button').onclick=()=>{blocked=true;renderGuide();};$('#close-guide').onclick=()=>$('#guide-dialog').close();$('#guide-dialog').addEventListener('close',()=>window.speechSynthesis?.cancel());
$('#speak').onclick=()=>{const speech=window.speechSynthesis,voice=speech?.getVoices().find(v=>v.lang.toLowerCase().startsWith(lang==='ja'?'ja':'zh'));if(!voice){$('#guide-message').textContent=t('対応音声がありません。画面を確認。','没有可用音色，请阅读文字。');return;}const g=getBrief(currentGuide,lang,blocked),u=new SpeechSynthesisUtterance(g.action+'。'+g.points.map(p=>p.text).join('。'));u.voice=voice;u.lang=voice.lang;u.onerror=()=>{$('#guide-message').textContent=t('読上げ失敗。','朗读失败，请阅读文字。');};speech.cancel();speech.speak(u);};
function openAlert(a){activeAlert=a;renderAlert();show($('#alert-dialog'));}
function renderAlert(){if(!activeAlert)return;const live=snapshotAlerts(snapshot).find(e=>eventKey(e)===eventKey(activeAlert)),a=alertView(live||activeAlert,live?snapshot:null,lang);$('#alert-title').textContent=a.name;$('#alert-state').textContent=a.stateLabel;$('#alert-area').textContent=a.city;$('#alert-metrics').replaceChildren(...a.metrics.flatMap(m=>[node('dt','',m.label),node('dd','',m.value)]));$('#alert-countdown').textContent=countdown(a,live?snapshot:null,lang);$('#alert-time').textContent=a.time+' · '+a.publisher;$('#alert-message').textContent=a.timingNote||'';$('#alert-source').href=a.source;}
$('#close-alert').onclick=()=>$('#alert-dialog').close();$('#alert-guide').onclick=()=>openGuide(activeAlert.hazard);$('#alert-shelters').onclick=()=>openShelters(activeAlert.hazard);$('#guide-shelters').onclick=()=>openShelters(currentGuide);
function openShelters(hazard){shelterRequest++;$('#shelter-hazard').value=SHELTER_TYPES[hazard]?hazard:'';$('#shelter-results').replaceChildren();$('#shelter-message').textContent=t('実際の災害種別を選んで現在地を確認。','选择实际灾种后查询当前位置。');show($('#shelter-dialog'));}
$('#close-shelters').onclick=()=>{shelterRequest++;$('#shelter-dialog').close();};$('#shelter-hazard').onchange=()=>{shelterRequest++;$('#shelter-results').replaceChildren();};
$('#find-shelters').onclick=async()=>{const hazard=$('#shelter-hazard').value;if(!hazard){$('#shelter-message').textContent=t('まず災害種別を選択。','请先选择具体灾种。');return;}const id=++shelterRequest;$('#find-shelters').disabled=true;$('#shelter-message').textContent=t('現在地と避難場所を確認中…','正在获取当前位置和避难地点…');try{const position=await requestPosition(navigator.geolocation);const result=await nearbyShelters(position,hazard,true);if(id!==shelterRequest)return;$('#shelter-message').textContent=result.places.length?t('直線距離順。開設・経路の通行可否は未確認。','按直线距离排序；开放状态与道路可通行性未核实。'):t('対応する場所が取得できません。標識・自治体情報に従う。','未取得适合该灾种的地点，请按现场标识和当地政府信息行动。');$('#shelter-results').replaceChildren(...result.places.map(p=>{const box=node('div','shelter-result');box.append(node('h3','',p.name),node('p','',(p.distanceMeters/1000).toFixed(2)+' km · '+p.address));if(p.remarks)box.append(node('p','',p.remarks));if(Number.isFinite(p.elevationMeters))box.append(node('p','',t('地面の標高 約 ','地面海拔约 ')+p.elevationMeters+' m · '+t('建物の避難階の高さではありません','不是建筑避难楼层的高度')));box.append(node('p','',t('地図経路は安全の保証ではありません。冠水・通行止めには進まない。','地图路线不保证安全；遇积水或封路不要继续前行。')));const a=link(t('徒歩ナビを開く ↗','立即导航前往 ↗'),navigationURL(p));a.className='button';box.append(a,link(t(' 地理院データ ↗',' 国土地理院数据 ↗'),p.source));return box;}));}catch(e){if(id===shelterRequest)$('#shelter-message').textContent=locationError(e,lang);}finally{$('#find-shelters').disabled=false;}};
function renderSources(){const blocks=[
 [t('気象庁 公開XML','气象厅公开 XML'),t('約1分の更新周期。秒単位の緊急地震速報は未接続。未取得を安全や解除と解釈しない。','约每分钟更新；秒级紧急地震预警未接通。未取得记录不代表安全或解除。'),'https://xml.kishou.go.jp/xmlpull.html'],
 [t('災害別の避難場所','按灾种选择避难场所'),t('国土地理院の指定緊急避難場所。津波は津波対応のみ。開設・通行可否・安全な経路は未確認。','国土地理院指定紧急避难场所。海啸只列津波适用地点；开放状态、道路与安全路线未核实。'),'https://www.gsi.go.jp/bousaichiri/hinanbasho'],
 [t('郵便番号と場所','邮编与所在地'),t('日本郵便2026年8月31日データ。市町村候補に変換し、ユーザーが確認。GPSや住所の原文は保存しない。','日本邮便2026年8月31日数据，转换为市町村候选后由用户确认。GPS和原始地址不持久保存。'),'https://www.post.japanpost.jp/service/search/zipcode/download/utf-zip.html'],
 [t('眼鏡と配信','眼镜与信息推送'),t('このWeb画面は表示中だけ更新。常時配信は別サービスとRokid端末検証が必要。','此网页仅在显示时更新。常驻推送需要另行接通服务，并在 Rokid 真机验证。'),'https://js.rokid.com/AIUI/cloud/notifications?version=0.17.0']
 ];$('#sources-content').replaceChildren(...blocks.map(([h,p,u])=>{const b=node('div','source-block');b.append(node('h3','',h),node('p','',p),link(t('公式資料 ↗','官方说明 ↗'),u));return b;}));}
function translate(){document.documentElement.lang=lang==='zh'?'zh-CN':'ja';document.querySelectorAll('[data-ja]').forEach(n=>n.textContent=(n.dataset[lang]||n.dataset.ja).replaceAll('\\n','\n'));$('#language').textContent=lang==='ja'?'日本語 / 中文':'中文 / 日本語';$('#greeting').textContent=t('住所・郵便番号から所在地を確認できます。危険な状況は下の入力欄でも伝えられます。','先通过地址或邮编确认所在地。也可在下方描述危险情况，直接打开离线应对指南。');$('#shelter-hazard').replaceChildren(option(t('— 災害種別 —','— 选择灾种 —'),''),...Object.entries(SHELTER_TYPES).map(([code,l])=>option(l[lang==='zh'?1:0],code)));hazards();renderSources();renderData();updateHud();if(currentGuide)renderGuide();if(activeAlert)renderAlert();tick();}
function ask(input){const text=String(input).trim().slice(0,500);if(!text)return;$('#chat').append(node('p','user-message',text));const r=classifyIntent(text);if(r.intent==='weather')refresh();else if(r.intent==='unknown'){$('#address-query').value=text;findAddress();}else{const g=getBrief(r.intent,lang,r.blocked);$('#chat').append(node('p','assistant-message',g.action));openGuide(r.intent,r.blocked);}$('#question').value='';$('#chat').scrollTop=$('#chat').scrollHeight;}
$('#chat-form').onsubmit=e=>{e.preventDefault();ask($('#question').value);};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>ask(lang==='zh'?b.dataset.zh:b.dataset.prompt));
function switchView(view){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==view+'-view');document.querySelectorAll('.nav-button').forEach(e=>e.classList.toggle('active',e.dataset.view===view));}
$('.brand').onclick=e=>{e.preventDefault();switchView('overview');};document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#language').onclick=()=>{lang=lang==='ja'?'zh':'ja';localStorage.setItem('mamori-language',lang);translate();};
function tick(){$('#clock').textContent=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())+' JST';$('#network').textContent=navigator.onLine?t('通信環境あり','网络可用'):t('オフライン','离线模式');if($('#alert-dialog').open)renderAlert();}
window.addEventListener('offline',()=>{request++;busy=false;$('#refresh').disabled=false;snapshot=null;tick();renderData();});window.addEventListener('online',()=>{tick();if(selected)refresh();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&selected&&!isSnapshotFresh(snapshot))refresh();});setInterval(()=>{if(!document.hidden&&navigator.onLine&&selected&&!busy)refresh();},60000);setInterval(()=>{tick();if(!busy)renderData();},15000);setInterval(()=>{if($('#alert-dialog').open)renderAlert();},1000);
if(selected){$('#office').value=selected.officeCode;fillCities();}translate();if(selected)refresh();
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
