"""Build offline municipality lookup from attributed official local snapshots."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
a=json.loads((root/'data/areas.json').read_text())
g=json.loads((root/'data/gsi-municipalities.json').read_text())
rows=[]
for code,c in a['class20s'].items():
 district=a['class15s'][c['parent']]['parent'];office_code=a['class10s'][district]['parent'];o=a['offices'][office_code]
 rows.append([code,c['name'],c.get('enName',''),c.get('kana',''),office_code,o['name'],o.get('enName',''),district])
content='// Generated by scripts/build-locations.py. JMA area.json and GSI muni.js, 2026-09-11.\n'
content+='export const CITY_ROWS = '+json.dumps(rows,ensure_ascii=False,separators=(',',':'))+';\n'
content+='export const GSI_MUNICIPALITIES = '+json.dumps(g,ensure_ascii=False,separators=(',',':'))+';\n'
(root/'agent/modules/location-data.js').write_text(content)
print('Bundled municipalities:',len(rows))

# Keep the two attributed lookup snapshots reproducible alongside municipalities.
population=json.loads((root/'data/prefecture-population.json').read_text())
(root/'agent/modules/population.js').write_text(
    '// Statistics Bureau prefecture totals. Source and scope: data/prefecture-population.json\n'
    +'export const POPULATION_DATE='+json.dumps(population['asOf'])+';\n'
    +'export const PREFECTURE_POPULATIONS='+json.dumps(population['populations'],separators=(',',':'))+';\n')
stations=json.loads((root/'data/forecast-stations.json').read_text())
(root/'agent/modules/forecast-stations.js').write_text(
    '// JMA forecast/const/forecast_area.json, retrieved 2026-09-11. Representative forecast stations, not user measurements.\n'
    +'export const FORECAST_STATIONS='+json.dumps(stations,ensure_ascii=False,separators=(',',':'))+';\n')
