from pathlib import Path
import re,json,shutil
R=Path(__file__).resolve().parents[1];O=R/'output/posters/japanese'
css=re.search(r'<style>(.*?)</style>',(R/'output/posters/concise/ikeda.html').read_text(),re.S)[1]
css+='body{font-family:"Hiragino Kaku Gothic ProN","Hiragino Sans",Meiryo,sans-serif}.hero h1{font-size:61px}.caption b{font-size:21px}.caption span{font-size:16px}.benefit strong{font-size:23px}.benefit small{font-size:15px}.note{font-size:15px}'
scenes=[dict(id='ikeda',type='地震',title='揺れたら、まず身を守る。',place='大阪府 池田市',accent='#b76725',tint='#f3e8d9',state='地震情報を表示',benefits=[('!','天気から災害情報へ','状況に応じてホームの表示が変わる'),('◎','地域に合った情報','震度とマグニチュードを分けて表示'),('＋','行動を一画面で','身を守ってから情報を確認')],note='すべて訓練データです。ホームは自動遷移前を一時停止して撮影。地震情報は発生後の情報です。'),dict(id='wakayama',type='火山・架空の訓練',title='警戒情報を確認。規制に従う。',place='和歌山県・架空の想定',accent='#b05238',tint='#f3e5df',state='噴火警報を表示',benefits=[('!','警戒情報をホームに','噴火警報を確認しやすく'),('△','レベルと規制を確認','警戒レベルと規制内容を分けて表示'),('＋','取るべき行動を確認','自治体と現場の指示に従う')],note='和歌山県と周辺に活火山はありません。本図は架空の訓練で、地域のリスク評価ではありません。'),dict(id='iwate',type='地震 ＋ 津波',title='波を待たず、すぐ避難。',place='岩手県沿岸・宮古市',accent='#246b91',tint='#e1edf4',state='津波・地震を表示',benefits=[('≋','津波情報を優先','複数の災害情報から優先表示'),('◎','対象の沿岸を確認','市町村と津波予報区を別々に確認'),('＋','警報や時刻を待たない','揺れから身を守り、その後すぐ高台へ')],note='すべて訓練データです。ホームは自動遷移前を一時停止して撮影。ガイドはボタン操作で開きます。')]
for s in scenes:
 benefits=''.join(f'<div class="benefit"><i>{a}</i><div><strong>{b}</strong><small>{c}</small></div></div>' for a,b,c in s['benefits'])
 body=f'''<main class="poster" style="--accent:{s['accent']};--tint:{s['tint']}"><header class="top"><div class="brand"><span class="brandmark">守</span><div><strong>まもり MAMORI</strong><small>Rokid Glasses 向け防災エージェント</small></div></div><div class="stamp">実際の Ink 画面を撮影<br>開発中の試作版・訓練シナリオ</div></header><div class="hero"><div><p class="eyebrow">{s['type']}</p><h1>{s['title']}</h1></div><p class="place">{s['place']}</p></div><div class="groups"><section><div class="grouphead"><strong>ふだん</strong><span>天気を確認・備える</span></div><img class="screen" src="screens/{s['id']}-daily.png" alt="日常のホーム画面"><div class="caption"><b>日常のホーム</b><span>天気と日ごろの備え</span></div></section><section><div class="grouphead danger"><strong>災害時の想定</strong><span>ホームの変化 → 災害情報 → 行動ガイド</span></div><div class="row"><figure><img class="screen" src="screens/{s['id']}-warning.png" alt="災害情報表示に切り替わったホーム"><figcaption class="caption"><b style="color:var(--accent)">ホームが切替</b><span>{s['state']}</span></figcaption></figure><figure><img class="screen" src="screens/{s['id']}-alert.png" alt="災害情報の詳細"><figcaption class="caption"><b>災害情報</b><span>必要な情報をまとめて</span></figcaption></figure><figure><img class="screen" src="screens/{s['id']}-guide.png" alt="災害別の行動ガイド"><figcaption class="caption"><b>行動ガイド</b><span>最初の行動と３つの要点</span></figcaption></figure></div></section></div><div class="benefits">{benefits}</div><p class="note {'volcano' if s['id']=='wakayama' else ''}">{s['note']}</p><footer class="footer"><p>画面は訓練用です。実際の警報や眼鏡での実写ではありません。緊急時は公式情報と現場の指示に従ってください。<br>実機・バックグラウンド通知は未検証。秒単位の緊急地震速報とナビの自動起動は未接続です。</p><div class="folio">MAMORI / v0.2.2<br>{s['type']}</div></footer></main>'''
 (O/f'{s["id"]}-ja.html').write_text(f'<!doctype html><html lang="ja"><meta charset="utf-8"><title>まもり・{s["place"]}</title><style>{css}</style><body>{body}</body></html>')
print('Three Japanese horizontal layouts ready.')
